name: Release WebAssembly Module

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Pull latest tags
      run: git fetch --prune --unshallow --tags

    - name: Check if tag to be created does not yet exist
      run: |
        TAG=v$(awk '$1 == "version" {print $3}' Cargo.toml  | head  | tr -d "\"" | head -n1)
        if git rev-parse $TAG >/dev/null 2>&1; then
          echo "Tag $TAG already exists"
          exit 1
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV
      continue-on-error: true

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
      if: env.TAG

    - name: Install wasm-pack
      run:  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      if: env.TAG

    # Only release if the tests pass
    - name: Run tests
      run: make test
      if: env.TAG

    - name: Build
      run: make build
      if: env.TAG

    - name: Log in to NPM
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: env.TAG

    - name: Publish to NPM
      working-directory: pkg
      run: npm publish
      if: env.TAG

    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: pkg/*
        draft: true
        fail_on_unmatched_files: true
        generate_release_notes: true
        tag_name: ${{ env.TAG }}
      if: env.TAG
